# Generated by Django 5.0.1 on 2024-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_transaction_reciever_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("received", "Received"),
                    ("withdraw", "withdraw"),
                    ("refund", "Refund"),
                    ("request", "Payment Request"),
                    ("none", "None"),
                ],
                default="none",
                max_length=100,
            ),
        ),
    ]
